// pages/contact.vue
<template>
  <div class="mx-auto container">
    <Header/>
    <div class="text-base m-5 text-gray-800">
      <h1 class="text-3xl my-2">How to contact me?</h1>
      <h2 class="text-2xl my-1.5">Twitter or Discord</h2>
      <p>Twitter or Discord DM is the fastest way to get a response.</p>
      <ul class="m-3">
        <li>Twitter: <a class="text-blue-500 hover:text-blue-700" href="https://twitter.com/siroshun09">Siroshun09</a>
        </li>
        <li>Discord: <code class="bg-gray-200 px-1 rounded">Siroshun09#7501</code>
          (id: <code class="bg-gray-200 px-1 rounded">340865494406004737</code>)
        </li>
      </ul>
      <p>However, I may temporarily stop receiving messages due to spam or other reasons.</p>
      <h2 class="text-2xl my-1.5">E-mail</h2>
      <p>If you would like to communicate via email, please contact me at
        <code class="bg-gray-200 px-1 rounded">siroshun@pm.me</code> or
        <code class="bg-gray-200 px-1 rounded">siroshun@protonmail.com</code>.</p>
      <p>I will sign the email. Use
        <!--suppress HtmlUnknownTarget -->
        <a class="text-blue-500 hover:text-blue-700" href="mail_pgp.asc">
          this PGP key
        </a>
        to verify my signature.
      </p>
    </div>
  </div>
</template>

<script>
import Header from "~/components/Header";

export default {
  name: "contact",
  components: {Header}
}
</script>

// src/components/profile/Contact/index.tsx
import { KarlaFont } from "../../../fonts/KarlaFont";
import { RubikFont } from "../../../fonts/RubikFont";

export type Props = {
	onClickBack: () => void;
};

export const Contact = (props: Props) => {
	return (
		<div>
			<KarlaFont>
				<h1 className="text-4xl mt-3 mb-5 mx-auto px-1 py-2 text-gray-500 border-b border-gray-300 tracking-wider">
					How to contact me?
				</h1>
			</KarlaFont>

			<RubikFont>
				<p className="text-lg">
					X (Twitter) or Discord DM is the quickest way to get a response.
				</p>

				<ul className="text-lg my-3">
					<li>
						X (Twitter):{" "}
						<a
							className="text-blue-500 hover:text-blue-700"
							href="https://x.com/siroshun09"
						>
							Siroshun09
						</a>
					</li>
					<li>
						Discord:{" "}
						<code className="bg-gray-200 px-1 rounded text-gray-700 tracking-wider">
							siroshun
						</code>
					</li>
				</ul>

				<p className="text-lg">
					If you are using Discord, please send me a friend request first.
				</p>

				<hr className="my-3 text-gray-200" />

				<div className="text-center">
					<small className="text-base">
						<button
							className="text-blue-500 hover:text-blue-700 cursor-pointer"
							onClick={props.onClickBack}
							type="button"
						>
							Click here
						</button>{" "}
						to back to profile card
					</small>
				</div>
			</RubikFont>
		</div>
	);
};
